dataset: ogbg-molhiv
aug: baseline
model_type: gnn-transformer

gnn_type: gin
gnn_virtual_node: true
batch_size: 256
start-eval: 1

graph_pooling: cls

lr: 0.0001

seed: 12344

transformer_norm_input: true

runs: 10
epochs: 100

d_model: 128
dim_feedforward: 256
num_encoder_layers: 4
scheduler: plateau

transformer_dropout: 0.1
gnn_dropout: 0.3
gnn_JK: cat