dataset: MUTAG
aug: baseline
model_type: gnn-transformer

gnn_type: gin
gnn_virtual_node: false

graph_pooling: cls

lr: 0.0001

seed: 12344

transformer_norm_input: true

runs: 1
epochs: 10

d_model: 128
dim_feedforward: 64
num_encoder_layers: 2
scheduler: cosine

transformer_dropout: 0.1
gnn_dropout: 0.1
